node ("$JenkinNodeID") {
stage ('Clean workspace')
              {
              cleanWs() 
              }
        stage ('Code Checkout') {
          /* groovylint-disable-next-line TrailingComma */
              checkout([
             $class: 'SubversionSCM',

              additionalCredentials: [],

              excludedCommitMessages: '',

              excludedRegions: '',

              excludedRevprop: '',

              excludedUsers: '',

              filterChangelog: false,

              ignoreDirPropChanges: false,

              includedRegions: '',

                locations: [[cancelProcessOnExternalsFail: true,

                  credentialsId: "$SCM_Cred_ID",

                  depthOption: 'infinity',

                  ignoreExternalsOption: true,

                  local: '.',

                  remote: '$SCM_checkout']],

                quietOperation: true, workspaceUpdater: [$class: 'CheckoutUpdater']])
				
				
          }
          def  artifact = readMavenPom().getArtifactId()
          def  VERSION = readMavenPom().getVersion()
          def  packaging = readMavenPom().getPackaging()
          def  AppBuildName = "${artifact}"+"."+"${packaging}"
		  sh(script: "svn info --show-item revision . > tmp_svn")
		  sh(script: "echo '$SCM_checkout ' | rev | grep -Eo '[0-9]{4}+' | rev > tmp_sprint")
          def svnRevision = readFile('tmp_svn').trim()

stage ('Print SvnRevision SvnUrl and JenkinsJobNumber')
{
sh '''
echo test && \
myvarsprint=`cat tmp_sprint` && \
cd $FilePath && \
sed -i "s|@DevopsSPRINT_NUMBER|${myvarsprint}|g" $FileName '''
echo "BUILD_NUMBER=${env.BUILD_NUMBER}"
sh '''cd $FilePath && \
sed -i "s|@DevopsBUILD_NUMBER|${BUILD_NUMBER}|g" $FileName'''
sh '''
myvar=`cat tmp_svn` && \
cd $FilePath && \
sed -i 's|@DevopsREVISION_NUMBER|'${myvar}'|g' $FileName'''  
//sh '''
//myvarversion=`cat pom.xml | grep "<version>.*</version>" | head -2 | grep -v ".RELEASE"  |awk -F'[><]' '{print $3}'` && \
//cd $FilePath && \
//sed -i "s|@DevopsPRODUCT_NUMBER|"${myvarversion}"|g" $FileName '''  
sh '''
myvarJIRAProjecKey="$JIRAProjecKey"
curl  --request GET \
--url 'https://trinitymobilitypvtltd.atlassian.net/rest/api/2/project/"$myvarJIRAProjecKey"/version' \
--user 'bhargava.t@trinitymobility.com:9bHN5fTzf3gdpsWfjwtz3106' \
--header 'Accept: application/json' | python -mjson.tool  > AppJiraRelease.json
myvarAppJiraRelease=`egrep -i -B 3 '"released": true' AppJiraRelease.json | grep -i version | tail -1 | grep -Eo '[0-9\\.]+' | rev` && \
cd $FilePath && \
sed -i 's|@DevopsREVISION_NUMBER|'V${myvarAppJiraRelease}'|g' $FileName'''                 
			 }			 
}   
