node ("$JenkinNodeID") {
stage ('Clean workspace') {
cleanWs()
}
stage ('Update Nexus Repo Stable Snapshot') {
sh '''
curl -u "$NexusUserID":"$NexusUserPass" http://$NexusUrl/repository/$NexusRepoID/QA/latest/$Artifact_Product/$BuildName -o $BuildName
curl -v -u "$NexusUserID":"$NexusUserPass" --upload-file $BuildName http://$NexusUrl/repository/$NexusRepoID/QA/stable/$Artifact_Product/$BuildName
'''
}
echo"$isDeploymentReq"
if("$isDeploymentReq" == 'true')
        {
stage ('Deployment to QA Environment') {
          stageName = 'Deployment to QA Environment'
          deploy adapters: [tomcat8(credentialsId: "$tomcatToken",
          url: "$tomcatUrl")],
          contextPath: "$contextPath",
          war: '**/*.war'
        }
		}
}

