node ("$JenkinNodeID") {
  try {
        stage ('Code Checkout') {
          checkout([
             $class: 'SubversionSCM',

              additionalCredentials: [],

              excludedCommitMessages: '',

              excludedRegions: '',

              excludedRevprop: '',

              excludedUsers: '',

              filterChangelog: false,

              ignoreDirPropChanges: false,

              includedRegions: '',

                locations: [[cancelProcessOnExternalsFail: true,

                  credentialsId: "$SCM_Cred_ID",

                  depthOption: 'infinity',

                  ignoreExternalsOption: true,

                  local: '.',

                  remote: '$SCM_checkout']],

                quietOperation: true, workspaceUpdater: [$class: 'CheckoutUpdater']])
          }

        stage ('npm Dependencies Installation') {
            stageName = 'npm Dependencies Installation'
             sh '''bash
				. ~/.nvm/nvm.sh && . ~/.profile && nvm install $nodejsVersion && \
				npm update "$npmBuildParam" && npm install "$npmBuildParam" && \
                  npm install -D typescript && \
                  npm install'''
             }
                                 
             

        stage ('Complie, Build Client Libraries') {
            stageName = 'Build Execution'
             sh '''bash
				. ~/.nvm/nvm.sh && . ~/.profile && nvm install $nodejsVersion && \
					npm run ng build "$ngBuildParam"'''
            }
        stage ('Package Client Libraries') {
            stageName = 'Package Client Libraries'
            zip archive: true, dir: 'dist/'+"$BuildName", glob: '', zipFile: "$BuildName"+'.war'
            }

        if("$NexusRepoReq" == 'true'){
        stage ('Update Nexus Repo Latest Snapshot') {
		      if("$BuildWithVerNo" == 'true')
              {

              nexustarget = 'http://'+"$NexusUrl"+'/repository/'+"$NexusRepoID"+'/Dev/latest/'+"$Artifact_Product"+'/'+"${VERSION}"+'/'+"$BuildName"+'.war'
              finalOut = "$BuildName"+'.war'+' '+"${nexustarget}"
              echo "${nexustarget}"
              echo "${finalOut}"

          sh 'curl -v -u "$NexusUserID":"$NexusUserPass" --upload-file '+"${finalOut}"
          }
		  else
		  {
		  nexustarget = 'http://'+"$NexusUrl"+'/repository/'+"$NexusRepoID"+'/Dev/latest/'+"$Artifact_Product"+'/'+"$BuildName"+'.war'
              finalOut = "$BuildName"+'.war'+' '+"${nexustarget}"
              echo "${nexustarget}"
              echo "${finalOut}"

          sh 'curl -v -u "$NexusUserID":"$NexusUserPass" --upload-file '+"${finalOut}"
          }
              }
			  }
if("$isDockerBuildReq" == 'true')
       {
          stage ('DockerBuild') {
          stageName = 'Application Build Packaging'
           sh """mkdir target && cp *.war target/ && docker build \
           -t ${BuildName.toLowerCase()} \
           --no-cache ."""
        }
        }
        if("$isDockerPushReq" == 'true')
        {
         stage ('DockerPush') {
         stageName = 'Application Build Packaging'
         sh """docker login -u $NexusUserID -p $NexusUserPass repo.trinityiot.in:8123 && docker tag ${BuildName.toLowerCase()} repo.trinityiot.in:8123/${NexusRepoID.toLowerCase()}/${Artifact_Product.toLowerCase()}/${BuildName.toLowerCase()}:$VERSION && docker push repo.trinityiot.in:8123/${NexusRepoID.toLowerCase()}/${Artifact_Product.toLowerCase()}/${BuildName.toLowerCase()}:$VERSION"""
        }
        }		  
		currentBuild.result = 'SUCCESS'
          }
          catch (e) { 
            currentBuild.result = 'FAILURE'
              Builderror = "${e}"
              stage ('Report Error Status into JIRA') {
              /*  summarymsg = 'Application '+"${AppBuildName}"+' Build Failure in ' + "${stageName}" + ' Stage, Please take action Immediatly'
                descriptionmsg = 'Build failure due to ' + "${Builderror}"+' Refer Jenkin Job'+"${env.JOB_NAME}"
                echo "${Builderror}"
                echo "${summarymsg}"
                echo "${descriptionmsg}"
                echo "${JIRAProjecKey}"
                  def issue = [fields: [ project: [key: "${JIRAProjecKey}"],
                      summary:  "${summarymsg}",
                      description: "${descriptionmsg}",
                      issuetype: [name: 'Bug'],
                      assignee: [id: "${JiraDeveloperID}"]]]
                  response = jiraNewIssue issue: issue, site: "${JiraSite}"
                  echo response.successful.toString()
                  echo response.data.toString()
				  */
				  }				  
            }
              stage ('Finishing: Sitback and Relax')
              {
              cleanWs() 
              }
              }