- name: Stop Tomcat Service
  hosts: {{tomcatServerIP}}
  tasks:
    - name: Stop Service
      win_service:
        name: {{ServiceID}}
        state: stopped
    - name: Copy build to tomcat
      win_copy:
        src: {{ApplicationSrcDirs}}
        dest: {{tomcatDir}}
    - name: start Tomcat Service
      win_service:
        name: {{ServiceID}}
        state: started

