pipeline {
    agent { label 'master' }
    /* environment {
        CI = '"${CI}"'
        API_DIR = '"${API_DIR}"'
        DEV_ENV = '"${DEV_ENV}"'
        PROD_ENV = '"${PROD_ENV}"'
        TEST_SCRIPT_FILE = '"${TEST_SCRIPT_FILE}"'       
    }
	*/
    stages {
        stage('Code Checkout') {
            steps{
               /* groovylint-disable-next-line TrailingComma */
          checkout([
             $class: 'SubversionSCM',

              additionalCredentials: [],

              excludedCommitMessages: '',

              excludedRegions: '',

              excludedRevprop: '',

              excludedUsers: '',

              filterChangelog: false,

              ignoreDirPropChanges: false,

              includedRegions: '',

                locations: [[cancelProcessOnExternalsFail: true,

                  credentialsId: "$SCM_Cred_ID",

                  depthOption: 'infinity',

                  ignoreExternalsOption: true,

                  local: '.',

                  remote: '$SCM_checkout']],

                quietOperation: true, workspaceUpdater: [$class: 'CheckoutUpdater']])
                }
        }
       /* stage('Deploy to Dev') {
            environment{
                RETRY = '80'
            }
            steps {
			   echo '$PROD_ENV'
                echo 'Logging into $DEV_ENV'
                withCredentials([usernamePassword(credentialsId: 'apim_dev', usernameVariable: 'DEV_USERNAME', passwordVariable: 'DEV_PASSWORD')]) {
                    sh 'apictl login $DEV_ENV -u $DEV_USERNAME -p $DEV_PASSWORD -k'                       
                }
                echo 'Deploying to $DEV_ENV'
                sh 'apictl import-api -f $API_DIR -e $DEV_ENV -k --preserve-provider --update --verbose'
            }
        }
		echo"$isDeploytoDevReq"
        if("$isRunTestsDevReq" == 'true')
       stage('Run Tests') {
            steps {
                echo 'Running tests in $DEV_ENV'
                sh 'newman run $API_DIR/$TEST_SCRIPT_FILE --insecure'
            }
        }
		*/
        stage('Deploy to Production') {
            environment{
                RETRY = '60'
            }
            steps {
			dir("${workspace}") {
                sh 'echo "Logging into $PROD_ENV"'
                withCredentials([usernamePassword(credentialsId: 'apim_prod', usernameVariable: 'PROD_USERNAME', passwordVariable: 'PROD_PASSWORD')]) {
                    sh 'apictl login $PROD_ENV -u $PROD_USERNAME -p $PROD_PASSWORD -k'                       
                }
                echo 'Deploying to Production'
                sh 'apictl import-api -f $API_DIR -e $PROD_ENV  --params $PROD_ENV/api_params.yaml -k --preserve-provider --update --verbose'
            }
        }
    }
	}
    post {
        cleanup {
            deleteDir()
            dir("${workspace}@tmp") {
                deleteDir()
            }
            dir("${workspace}@script") {
                deleteDir()
            }
        }
    }
}